create sequence test_seq;

INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES ('Derek', 'M', 'R');
/*
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (2, 'Lily', 'F', 'R');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (3, 'Nick', 'M', 'R');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (4, 'Aaron', 'M', 'L');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (5, 'Desmond', 'M', 'R');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (6, 'Benton', 'M', 'L');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (7, 'Joy', 'F', 'L');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (8, 'Martin', 'M', 'R');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (9, 'Ashlee', 'M', 'L');
INSERT INTO PlAYERS (PLAYERID, NAME, GENDER, MAINHAND) VALUES (10, 'Taylor', 'M', 'R');
*/

